CustomerKeyvanSafe/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    #admin url shoud change 
    path('newoldadminpanel/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.coming_soon, name='coming_soon'),
    path('<str:invalid_url>/', views.handle_404, name='handle_404'),
]

main/models.py
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

main/forms.py
from django import forms

class SubscribeForm(forms.Form):
    email = forms.EmailField(label='Email')

main/views.py
from django.shortcuts import render
from .forms import SubscribeForm
from .models import Subscriber

def coming_soon(request):
    form = SubscribeForm()
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            subscriber = Subscriber.objects.create(email=email)
            subscriber.save()
            return render(request, 'main/thank_you.html')
    return render(request, 'main/coming_soon.html', {'form': form})

def handle_404(request, invalid_url):
    return render(request, '404/404.html')

main/templates/main/coming_soon.html
{% extends 'base.html' %} {% block content %}
<div class="content">
  <div class="jumbotron text-center">
    <p>برای به روز ماندن در خبرنامه ما عضو شوید</p>
    <form
      class="form-inline justify-content-center"
      method="post"
      action="{% url 'main:coming_soon' %}"
    >
      {% csrf_token %}
      <div class="form-group mx-sm-3 mb-2">{{ form.email }}</div>
      <button type="submit" class="btn btn-primary mb-2">عضویت</button>
    </form>
  </div>
</div>

{% endblock %}

main/templates/main/thank_you.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<hr>
    <div class="content">
        <div class="jumbotron text-center">
            <h1 class="display-4">متشکریم</h1>
            <p class="lead">از اینکه در خبرنامه ما عضو شدید سپاسگزاریم</p>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Keyvan Safe</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="logo-container">
          <img src="{% static 'images/logo.jpg' %}" alt="Logo" class="logo">
        </div>
        <div class="contents">
          <h1 class="display-4">.منتظرمان باشید</h1>
          <p></p>
          <p class="lead">!در حال طراحی جامع ترین سایت تجهیزات ایمنی هستیم</p>
          <p class="lead">شگفت زده خواهید شد</p>
        </div>
    </div>
    
        <hr>
        <section>
            <div class="image-container">
                <img src="{% static 'images/clothes.png'%}" alt="Image 1" class="active-image" />
                <div class="image-text image-text1">Image 1 .</div>
        
                <img src="{% static 'images/firefighter.png' %}" alt="Image 2" />
                <div class="image-text image-text2">Image 2.</div>
        
                <img
                src="{% static 'images/hat.png' %}"
                alt="Image 3"
                />
                <div class="image-text image-text3">Image 3.</div>
        
                <img src="{% static 'images/Rectangle.png' %}" alt="Image 4" />
                <div class="image-text image-text4">Image 4.</div>
            </div>
        </section>
      
          <script>
            let currentImageIndex = 0;
            const images = document.querySelectorAll(".image-container img");
            const imageTexts = document.querySelectorAll(".image-text");

            function showNextImage() {
            images[currentImageIndex].classList.remove("active-image");
            imageTexts[currentImageIndex].classList.remove("active-text");

            currentImageIndex = (currentImageIndex + 1) % images.length;

            images[currentImageIndex].classList.add("active-image");
            imageTexts[currentImageIndex].classList.add("active-text");

            images.forEach((image, index) => {
                if (index === currentImageIndex) {
                image.classList.add("active-image");
                image.classList.remove("inactive-image");
                } else {
                image.classList.add("inactive-image");
                image.classList.remove("active-image");
                }
            });
            }

            function startSlideshow() {
            showNextImage();
            setTimeout(startSlideshow, 3000);
            }

            startSlideshow();


            
          </script>
        {% block content %} {% endblock %}
        
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>